# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#

development:
  PARSER_GIT_REPO_PATH: "/Users/fede/Desktop/test_remote"
  API_HOST: "http://localhost:3000"
  WORKER_HOST: "http://localhost:3002"
  WORKER_API_KEY: "CcfouGYmkBnRL71aqAp8"
  HARVESTER_CACHING_ENABLED: true
  HONEYBADGER_API_KEY: "cd199c3f"

production:
  PARSER_GIT_REPO_PATH: "/data/sites/harvester.uat.digitalnz.org/parsers.git"
  API_HOST: "http://api.uat.digitalnz.org"
  WORKER_HOST: "http://worker.uat.digitalnz.org"
  WORKER_API_KEY: "CcfouGYmkBnRL71aqAp8"
  HARVESTER_CACHING_ENABLED: true
  HONEYBADGER_API_KEY: "cd199c3f"

test:
  PARSER_GIT_REPO_PATH: "spec/fixtures/test_repo"
  API_HOST: "http://localhost:3000"
  WORKER_HOST: "http://localhost:3002"
  WORKER_API_KEY: "12345"
  HARVESTER_CACHING_ENABLED: false
  HONEYBADGER_API_KEY: "cd199c3f"