# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#

development:
  WORKER_HOST: "http://localhost:3002"
  WORKER_API_KEY: "CcfouGYmkBnRL71aqAp8"
  HARVESTER_CACHING_ENABLED: true
  HONEYBADGER_API_KEY: "cd199c3f"

production:
  WORKER_HOST: "http://worker.dnz03.digitalnz.org"
  WORKER_API_KEY: "rq6umzbPzPztcefxC8sX"
  HARVESTER_CACHING_ENABLED: true
  HONEYBADGER_API_KEY: "cd199c3f"

staging:
  WORKER_HOST: "http://worker.uat.digitalnz.org"
  WORKER_API_KEY: "rq6umzbPzPztcefxC8sX"
  HARVESTER_CACHING_ENABLED: true
  HONEYBADGER_API_KEY: "cd199c3f"

test:
  WORKER_HOST: "http://localhost:3002"
  WORKER_API_KEY: "12345"
  HARVESTER_CACHING_ENABLED: false
  HONEYBADGER_API_KEY: "cd199c3f"